# Generated by Django 3.1.7 on 2021-03-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena',
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='reseñaId',
            new_name='resenaId',
        ),
    ]
